### ISSUE TITLE
А есть какое нибудь описание как пользоваться

### ISSUE THREAD

**Issue by s-baklanov** [Kolyaj/CrossJS#2]
Например как использовать Function.debounce
Как я понял после подключения скрипта любая функция должна иметь в себе debounce
То есть создаю функцию 
function test(text) {
    alert(text);
}
потом можно 
test.debounce('test')
Но так не работает;
Как надо то ?

**Comment by Kolyaj** [comment]
debounce принимает таймаут, и возвращает новую функцию. Для вашего примера будет test.debounce(100)('test').
Но эта библиотека не поддерживается и не используется, лежит тут для истории.

**Comment by s-baklanov** [comment]
Большое спасибо. Теперь понятно
